apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-flask-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-flask-exporter
  template:
    metadata:
      labels:
        app: prometheus-flask-exporter
    spec:
      containers:
      - name: prometheus-flask-exporter
        image: custom-prometheus-flask-exporter #prebuilt: sg110/custom-prometheus-flask-exporter
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_APP
          value: "app.py"
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-flask-exporter-service
spec:
  selector:
    app: prometheus-flask-exporter
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
